COMP = {'England':{'Premier League':{'teams':'https://fbref.com/en/comps/9/Premier-League-Stats',
									 'games':'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'}},
		'France':{'Ligue 1':{'teams':'https://fbref.com/en/comps/13/Ligue-1-Stats',
									 'games':'https://fbref.com/en/comps/13/schedule/Ligue-1-Scores-and-Fixtures'}},
		'Spain':{'La Liga':{'teams':'https://fbref.com/en/comps/12/La-Liga-Stats',
									 'games':'https://fbref.com/en/comps/12/schedule/La-Liga-Scores-and-Fixtures'}},
		'Germany':{'Bundesliga':{'teams':'https://fbref.com/en/comps/20/Bundesliga-Stats',
									 'games':'https://fbref.com/en/comps/20/schedule/Bundesliga-Scores-and-Fixtures'}},
		'Italy':{'Serie A':{'teams':'https://fbref.com/en/comps/11/Serie-A-Stats',
									 'games':'https://fbref.com/en/comps/11/schedule/Serie-A-Scores-and-Fixtures'}},
		'Europe':{'Champions League':{'teams':'https://fbref.com/en/comps/8/Champions-League-Stats',
									 'games':'https://fbref.com/en/comps/8/schedule/Champions-League-Scores-and-Fixtures'},
				  'Europa League':{'teams':'https://fbref.com/en/comps/19/Europa-League-Stats',
									 'games':'https://fbref.com/en/comps/19/schedule/Europa-League-Scores-and-Fixtures'}}}